# IMPORTANT!
# Use `--env-file` agument during build with  `docker compose` to set arguments for Dockerfiles
# Example: docker compose --env-file=.env.tests -f ./docker-compose.tests.yaml up -d --build

services:
  # Run container with database
  fd_db_tests:
    build:
      context: ./backend/
      dockerfile: Dockerfile.db
    container_name: fd_db_tests
    restart: "no"
    env_file:
      - .env.tests
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGPORT=${DB_PORT}
    networks:
      - tests
    tmpfs:
      - /var/lib/postgresql/data

  # Run webserver with backend (API)
  # Tests run in the same container with `docker compose run --rm` command
  fd_backend_tests:
    build:
      context: ./backend/
      dockerfile: Dockerfile.backend
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    container_name: fd_backend_tests
    restart: "no"
    depends_on:
      - fd_db_tests
    env_file:
      - .env.tests
    environment:
      - BACKEND_HOST=fd_backend_tests
      - DB_HOST=fd_db_tests
    networks:
      - tests

# Tests use isolated docker network
networks:
  tests:
    internal: true
