# IMPORTANT!
# Use `--env-file` agument during build with  `docker compose` to set arguments for Dockerfiles
# Example: docker compose --env-file=.prod.tests -f ./docker-compose.prod.yaml up -d --build

services:
  # Run container with database
  fd_db_main:
    build:
      context: ./backend/
      dockerfile: Dockerfile.db
    container_name: fd_db_main
    restart: always
    env_file:
      - .env.prod
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - fd_db_main:/var/lib/postgresql/data

  # Run webserver with backend (API)
  fd_backend_prod:
    build:
      context: ./backend/
      dockerfile: Dockerfile.backend
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    container_name: fd_backend_prod
    restart: always
    depends_on:
      - fd_db_main
    env_file:
      - .env.prod
    environment:
      - DB_HOST=fd_db_main
    ports:
      - ${BACKEND_PORT}:8001
    healthcheck:
      disable: ${HEALTHCHECK_DISABLE}
      test: [ "CMD-SHELL", "curl -f ${BACKEND_URL}${HEALTHCHECK_URL}" ]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  # Database data is stored in volume
  fd_db_main:
    name: fd_db_main
