services:
  # Run container with database
  tests_db:
    build:
      context: ./backend/
      dockerfile: Dockerfile.db
    container_name: tests_db
    restart: "no"
    env_file:
      - tests.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - network_flash_tests

  # Run webserver with backend (API)
  # Tests run in the same container with `docker compose run --rm` command
  tests_backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.backend
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    container_name: tests_backend
    restart: "no"
    depends_on:
      - tests_db
    env_file:
      - tests.env
    environment:
      - BACKEND_HOST=tests_backend
      - DB_HOST=tests_db
    networks:
      - network_flash_tests

networks:
  network_flash_tests:
    internal: true
