# One click deployment

volumes:
  # local database is stored in volume
  flash_db:
    name: flash_db

services:
  # Run container with database
  flash_db:
    image: postgres:latest
    container_name: flash_db
    volumes:
      - flash_db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: always

  # Run webserver with backend (API)
  flash_backend:
    build: flash_backend/
    container_name: flash_backend
    restart: "no"
    depends_on:
      - flash_db
    ports:
      - ${BACKEND_PORT}:8001
    environment:
      - TZ=Europe/Moscow
      - DATABASE_URL=flash_db
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_USER=postgres
      - DATABASE_PASS=${DB_PASS}

  # Run webserver with frontend
  flash_frontend:
    build:
      context: ./flash_frontend/
      args:
        - BACKEND_URL=${BACKEND_URL}
    container_name: flash_frontend
    restart: "no"
    depends_on:
      - flash_db
      - flash_backend
    ports:
      - ${FRONTEND_PORT}:8000
  #
  # Run end2end tests
  # flash_tests:
  #   build:
  #     context: ./tests/
  #     args:
  #       - BACKEND_URL=${BACKEND_URL}
  #       - FRONTEND_URL=${FRONTEND_URL}
  #   container_name: flash_tests
  #   restart: "no"
  #   depends_on:
  #     - flash_db
  #     - flash_backend
  #     - flash_frontend
