FROM python:3.11

# Allow install additional packages
RUN apt-get update

# Install Poetry
RUN pip install poetry

# Create the app folder and copy the app's files
RUN mkdir -p /usr/src/backend
WORKDIR /usr/src/backend

# Copy dependency files
COPY poetry.lock pyproject.toml ./

# Install required Python libraries
RUN poetry install --with test

# Copy the app files
COPY . .
RUN rm -rf /usr/src/backend/tests/e2e
RUN poetry install
