"""decisions sessions users table

Revision ID: 252545db086b
Revises: 
Create Date: 2020-06-09 00:35:08.126307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252545db086b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('user_password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_email'), 'users', ['user_email'], unique=True)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=True)
    op.create_table('sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('session_status', sa.String(), nullable=True),
    sa.Column('session_datetime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('case_market', sa.String(), nullable=True),
    sa.Column('case_ticker', sa.String(), nullable=True),
    sa.Column('case_timeframe', sa.String(), nullable=True),
    sa.Column('case_barsnumber', sa.Integer(), nullable=True),
    sa.Column('case_timer', sa.Integer(), nullable=True),
    sa.Column('case_datetime', sa.DateTime(), nullable=True),
    sa.Column('case_iterations', sa.Integer(), nullable=True),
    sa.Column('case_slippage', sa.Float(), nullable=True),
    sa.Column('case_fixingbar', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_session_datetime'), 'sessions', ['session_datetime'], unique=False)
    op.create_table('decisions',
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('iteration_id', sa.Integer(), nullable=True),
    sa.Column('iteration_finishbar_datetime', sa.DateTime(), nullable=True),
    sa.Column('decision_action', sa.String(), nullable=True),
    sa.Column('decision_time', sa.Float(), nullable=True),
    sa.Column('decision_result_raw', sa.Float(), nullable=True),
    sa.Column('decision_result_corrected', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_decisions_session_id'), 'decisions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_session_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_sessions_session_datetime'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_user_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
