"""empty message

Revision ID: 634b8d85bfca
Revises: 59ca4717df8e
Create Date: 2022-02-06 01:16:17.495481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634b8d85bfca'
down_revision = '59ca4717df8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_User_UserName', table_name='User')
    op.create_index(op.f('ix_User_UserName'), 'User', ['UserName'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_UserName'), table_name='User')
    op.create_index('ix_User_UserName', 'User', ['UserName'], unique=False)
    # ### end Alembic commands ###
