"""empty message

Revision ID: 78dd505648c6
Revises: 
Create Date: 2021-08-22 01:59:11.300427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78dd505648c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(), nullable=True),
    sa.Column('UserEmail', sa.String(), nullable=True),
    sa.Column('UserPassword', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('UserId')
    )
    op.create_index(op.f('ix_User_UserEmail'), 'User', ['UserEmail'], unique=True)
    op.create_index(op.f('ix_User_UserId'), 'User', ['UserId'], unique=False)
    op.create_index(op.f('ix_User_UserName'), 'User', ['UserName'], unique=True)
    op.create_table('Session',
    sa.Column('SessionId', sa.Integer(), nullable=False),
    sa.Column('CreateDatetime', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('Market', sa.String(), nullable=True),
    sa.Column('Ticker', sa.String(), nullable=True),
    sa.Column('Timeframe', sa.String(), nullable=True),
    sa.Column('Barsnumber', sa.Integer(), nullable=True),
    sa.Column('Timelimit', sa.Integer(), nullable=True),
    sa.Column('SetFinishDatetime', sa.DateTime(), nullable=True),
    sa.Column('Iterations', sa.Integer(), nullable=True),
    sa.Column('Slippage', sa.Float(), nullable=True),
    sa.Column('Fixingbar', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['User.UserId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SessionId')
    )
    op.create_index(op.f('ix_Session_SessionId'), 'Session', ['SessionId'], unique=False)
    op.create_index(op.f('ix_Session_UserId'), 'Session', ['UserId'], unique=False)
    op.create_table('Iteration',
    sa.Column('IterationId', sa.Integer(), nullable=False),
    sa.Column('SessionId', sa.Integer(), nullable=True),
    sa.Column('IterationNum', sa.Integer(), nullable=True),
    sa.Column('FixingBarDatetime', sa.DateTime(), nullable=True),
    sa.Column('Action', sa.String(), nullable=True),
    sa.Column('TimeSpent', sa.Float(), nullable=True),
    sa.Column('ResultRaw', sa.Float(), nullable=True),
    sa.Column('ResultFinal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['SessionId'], ['Session.SessionId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('IterationId')
    )
    op.create_index(op.f('ix_Iteration_IterationId'), 'Iteration', ['IterationId'], unique=False)
    op.create_index(op.f('ix_Iteration_SessionId'), 'Iteration', ['SessionId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Iteration_SessionId'), table_name='Iteration')
    op.drop_index(op.f('ix_Iteration_IterationId'), table_name='Iteration')
    op.drop_table('Iteration')
    op.drop_index(op.f('ix_Session_UserId'), table_name='Session')
    op.drop_index(op.f('ix_Session_SessionId'), table_name='Session')
    op.drop_table('Session')
    op.drop_index(op.f('ix_User_UserName'), table_name='User')
    op.drop_index(op.f('ix_User_UserId'), table_name='User')
    op.drop_index(op.f('ix_User_UserEmail'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
