"""empty message

Revision ID: 99b2de58809b
Revises: f0e52ac8e062
Create Date: 2021-08-25 02:13:11.984928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b2de58809b'
down_revision = 'f0e52ac8e062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Session', sa.Column('FirstBarDatetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Session', 'FirstBarDatetime')
    # ### end Alembic commands ###
