"""empty message

Revision ID: a44d22fcebf8
Revises: 
Create Date: 2021-08-18 01:46:26.740960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44d22fcebf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(), nullable=True),
    sa.Column('UserEmail', sa.String(), nullable=True),
    sa.Column('UserPassword', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('UserId')
    )
    op.create_index(op.f('ix_User_UserEmail'), 'User', ['UserEmail'], unique=True)
    op.create_index(op.f('ix_User_UserId'), 'User', ['UserId'], unique=False)
    op.create_index(op.f('ix_User_UserName'), 'User', ['UserName'], unique=True)
    op.create_table('Session',
    sa.Column('SessionId', sa.Integer(), nullable=False),
    sa.Column('CreateDatetime', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('Market', sa.String(), nullable=True),
    sa.Column('Ticker', sa.String(), nullable=True),
    sa.Column('Timeframe', sa.String(), nullable=True),
    sa.Column('Barsnumber', sa.Integer(), nullable=True),
    sa.Column('Timelimit', sa.Integer(), nullable=True),
    sa.Column('SetFinishDatetime', sa.DateTime(), nullable=True),
    sa.Column('Iterations', sa.Integer(), nullable=True),
    sa.Column('Slippage', sa.Float(), nullable=True),
    sa.Column('Fixingbar', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['User.UserId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SessionId')
    )
    op.create_index(op.f('ix_Session_SessionId'), 'Session', ['SessionId'], unique=False)
    op.create_index(op.f('ix_Session_UserId'), 'Session', ['UserId'], unique=False)
    op.create_table('Decision',
    sa.Column('DecisionId', sa.Integer(), nullable=False),
    sa.Column('SessionId', sa.Integer(), nullable=True),
    sa.Column('IterationNum', sa.Integer(), nullable=True),
    sa.Column('IterationFixingBarDatetime', sa.DateTime(), nullable=True),
    sa.Column('DecisionAction', sa.String(), nullable=True),
    sa.Column('DecisionTime', sa.Float(), nullable=True),
    sa.Column('DecisionResultRaw', sa.Float(), nullable=True),
    sa.Column('DecisionResultFinal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['SessionId'], ['Session.SessionId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('DecisionId')
    )
    op.create_index(op.f('ix_Decision_DecisionId'), 'Decision', ['DecisionId'], unique=False)
    op.create_index(op.f('ix_Decision_SessionId'), 'Decision', ['SessionId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Decision_SessionId'), table_name='Decision')
    op.drop_index(op.f('ix_Decision_DecisionId'), table_name='Decision')
    op.drop_table('Decision')
    op.drop_index(op.f('ix_Session_UserId'), table_name='Session')
    op.drop_index(op.f('ix_Session_SessionId'), table_name='Session')
    op.drop_table('Session')
    op.drop_index(op.f('ix_User_UserName'), table_name='User')
    op.drop_index(op.f('ix_User_UserId'), table_name='User')
    op.drop_index(op.f('ix_User_UserEmail'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
