"""empty message

Revision ID: e8d289f8d563
Revises: 78dd505648c6
Create Date: 2021-08-25 00:06:37.379800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8d289f8d563'
down_revision = '78dd505648c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Decision',
    sa.Column('DecisionId', sa.Integer(), nullable=False),
    sa.Column('CreateDatetime', sa.DateTime(), nullable=True),
    sa.Column('SessionId', sa.Integer(), nullable=True),
    sa.Column('IterationId', sa.Integer(), nullable=True),
    sa.Column('Action', sa.String(), nullable=True),
    sa.Column('TimeSpent', sa.Float(), nullable=True),
    sa.Column('ResultRaw', sa.Float(), nullable=True),
    sa.Column('ResultFinal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['IterationId'], ['Iteration.IterationId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SessionId'], ['Session.SessionId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('DecisionId')
    )
    op.create_index(op.f('ix_Decision_DecisionId'), 'Decision', ['DecisionId'], unique=False)
    op.create_index(op.f('ix_Decision_IterationId'), 'Decision', ['IterationId'], unique=False)
    op.create_index(op.f('ix_Decision_SessionId'), 'Decision', ['SessionId'], unique=False)
    op.add_column('Iteration', sa.Column('CreateDatetime', sa.DateTime(), nullable=True))
    op.add_column('Iteration', sa.Column('StartBarDatetime', sa.DateTime(), nullable=True))
    op.add_column('Iteration', sa.Column('FinalBarDatetime', sa.DateTime(), nullable=True))
    op.drop_column('Iteration', 'ResultRaw')
    op.drop_column('Iteration', 'TimeSpent')
    op.drop_column('Iteration', 'Action')
    op.drop_column('Iteration', 'ResultFinal')
    op.add_column('Session', sa.Column('LastFixingBarDatetime', sa.DateTime(), nullable=True))
    op.drop_column('Session', 'SetFinishDatetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Session', sa.Column('SetFinishDatetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Session', 'LastFixingBarDatetime')
    op.add_column('Iteration', sa.Column('ResultFinal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('Iteration', sa.Column('Action', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Iteration', sa.Column('TimeSpent', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('Iteration', sa.Column('ResultRaw', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('Iteration', 'FinalBarDatetime')
    op.drop_column('Iteration', 'StartBarDatetime')
    op.drop_column('Iteration', 'CreateDatetime')
    op.drop_index(op.f('ix_Decision_SessionId'), table_name='Decision')
    op.drop_index(op.f('ix_Decision_IterationId'), table_name='Decision')
    op.drop_index(op.f('ix_Decision_DecisionId'), table_name='Decision')
    op.drop_table('Decision')
    # ### end Alembic commands ###
