"""empty message

Revision ID: f0aab77f7dde
Revises: fc3f5637108d
Create Date: 2022-04-04 19:50:35.995189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0aab77f7dde'
down_revision = 'fc3f5637108d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Decision', sa.Column('UserId', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Decision_UserId'), 'Decision', ['UserId'], unique=False)
    op.create_foreign_key('fk_Decision_UserId_User', 'Decision', 'User', ['UserId'], ['UserId'], ondelete='CASCADE')
    op.add_column('Session', sa.Column('Mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Session', 'Mode')
    op.drop_constraint('fk_Decision_UserId_User', 'Decision', type_='foreignkey')
    op.drop_index(op.f('ix_Decision_UserId'), table_name='Decision')
    op.drop_column('Decision', 'UserId')
    # ### end Alembic commands ###
