"""empty message

Revision ID: fc3f5637108d
Revises: 634b8d85bfca
Create Date: 2022-02-12 00:25:35.803918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc3f5637108d'
down_revision = '634b8d85bfca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Authentication',
    sa.Column('AuthId', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('AuthDatetime', sa.DateTime(), nullable=True),
    sa.Column('IpAddress', sa.String(), nullable=True),
    sa.Column('UserAgent', sa.String(), nullable=True),
    sa.Column('StatusCode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['User.UserId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('AuthId')
    )
    op.create_index(op.f('ix_Authentication_AuthId'), 'Authentication', ['AuthId'], unique=False)
    op.create_index(op.f('ix_Authentication_UserId'), 'Authentication', ['UserId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Authentication_UserId'), table_name='Authentication')
    op.drop_index(op.f('ix_Authentication_AuthId'), table_name='Authentication')
    op.drop_table('Authentication')
    # ### end Alembic commands ###
