"""empty message

Revision ID: 3c3e87d497da
Revises: f0aab77f7dde
Create Date: 2022-05-14 19:52:40.189058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c3e87d497da'
down_revision = 'f0aab77f7dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Iteration', sa.Column('JsonQuotes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Iteration', 'JsonQuotes')
    # ### end Alembic commands ###
