"""empty message

Revision ID: d16440742b31
Revises: 99b2de58809b
Create Date: 2021-08-28 14:29:21.818426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd16440742b31'
down_revision = '99b2de58809b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Iteration', sa.Column('StartBarNum', sa.Integer(), nullable=True))
    op.add_column('Iteration', sa.Column('FinalBarNum', sa.Integer(), nullable=True))
    op.add_column('Iteration', sa.Column('FixingBarNum', sa.Integer(), nullable=True))
    op.drop_column('Iteration', 'FinalBarDatetime')
    op.drop_column('Iteration', 'StartBarDatetime')
    op.add_column('Session', sa.Column('TotalSessionBars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Session', 'TotalSessionBars')
    op.add_column('Iteration', sa.Column('StartBarDatetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('Iteration', sa.Column('FinalBarDatetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Iteration', 'FixingBarNum')
    op.drop_column('Iteration', 'FinalBarNum')
    op.drop_column('Iteration', 'StartBarNum')
    # ### end Alembic commands ###
