"""decisions table

Revision ID: e6ef3d61c36c
Revises: b96a92fd148e
Create Date: 2020-06-06 22:13:13.782514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ef3d61c36c'
down_revision = 'b96a92fd148e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('decisions', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('decisions', 'session_iteration',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('decisions', 'session_iteration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('decisions', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
