"""init

Revision ID: 8a6e2da0cb65
Revises:
Create Date: 2023-04-27 23:28:04.789476

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8a6e2da0cb65"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User",
        sa.Column("Id", sa.Integer(), nullable=False),
        sa.Column("Name", sa.String(), nullable=False),
        sa.Column("Email", sa.String(), nullable=False),
        sa.Column("Password", sa.String(), nullable=False),
        sa.Column("DatetimeCreate", sa.DateTime(), nullable=False),
        sa.Column(
            "Status",
            postgresql.ENUM("active", "disabled", name="user_status", schema="production"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("Id"),
        schema="production",
    )
    op.create_index(
        op.f("ix_production_User_Email"), "User", ["Email"], unique=True, schema="production"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_production_User_Email"), table_name="User", schema="production")
    op.drop_table("User", schema="production")
    # ### end Alembic commands ###
